version: '3.3'

services:
  postgres:
    container_name: postgres
    image: postgres:13.5
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "USER_ADMIN"
      POSTGRES_PASSWORD: "USER_LOCAL"

