server:
  port: 8082

eureka:
  client:
    fetch-register: true
    register-with-eureka: true
    defaultZone: http://localhost:8761

spring:
  cloud:
    gateway:
      routes:
        - id: account
          uri: lb://server
          predicates:
            - Path=/account/**
