server:
  port: 7000
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/vitorhenriquec/spring-cloud
          search-paths: server-configurations
#Local:
#spring:
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
#          search-locations: ..\server-configurations
